# 1. My Web App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-blog-site-deployment
  labels:
    app: java-blog-site
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-blog-site
  template:
    metadata:
      labels:
        app: java-blog-site
    spec:
      containers:
      - name: java-blog-site
        image: swapnilmali101/java-blog-site-image:v
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: java-blog-site-service
spec:
  selector:
    app: java-blog-site
  ports:
    - port: 8087
      targetPort: 8087
  type: NodePort
---

# 2. Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: NodePort
---

# 3. Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
---
